version: '3'

services:
  bind9:
    build: .
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      - HOST_IP_ADDRESS=${HOST_IP_ADDRESS}
    volumes:
      - ./bind9-config/db.local.template:/etc/bind/db.local.template
      - ./bind9-config/named.conf.local:/etc/bind/named.conf.local